-- ============================================================
-- Better Auth core schema
-- ============================================================
-- Generated from src/lib/auth.ts, then reformatted. Only the layout is
-- hand-written: the tables, types, and constraints are Better Auth's own output
-- and must not be edited by hand.
--
-- After changing the Better Auth config or plugins, do not edit this file. Add
-- a new migration with the delta, which the CLI will print for you:
--
--   docker compose up -d
--   DATABASE_URL=... bunx @better-auth/cli generate --config src/lib/auth.ts
--
-- The CLI introspects a live database, so it needs one running and will fail
-- with ECONNREFUSED otherwise. Pointed at an already-migrated database it emits
-- only what is missing, which is exactly what the new migration should contain.
--
-- Note: "user".id is text (Better Auth's default id is a random string, not a
-- uuid), so every user_id column in later migrations is text as well.

create table "user" (
  "id"            text        not null primary key,
  "name"          text        not null,
  "email"         text        not null unique,
  "emailVerified" boolean     not null,
  "image"         text,
  "createdAt"     timestamptz not null default current_timestamp,
  "updatedAt"     timestamptz not null default current_timestamp
);

create table "session" (
  "id"        text        not null primary key,
  "expiresAt" timestamptz not null,
  "token"     text        not null unique,
  "createdAt" timestamptz not null default current_timestamp,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId"    text        not null references "user" ("id") on delete cascade
);

create table "account" (
  "id"                    text        not null primary key,
  "accountId"             text        not null,
  "providerId"            text        not null,
  "userId"                text        not null references "user" ("id") on delete cascade,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  "password"              text,
  "createdAt"             timestamptz not null default current_timestamp,
  "updatedAt"             timestamptz not null
);

create table "verification" (
  "id"         text        not null primary key,
  "identifier" text        not null,
  "value"      text        not null,
  "expiresAt"  timestamptz not null,
  "createdAt"  timestamptz not null default current_timestamp,
  "updatedAt"  timestamptz not null default current_timestamp
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");
