import type { MetadataRoute } from "next";
import { site } from "@/config/site";

/**
 * The web app manifest, served at /manifest.webmanifest. It controls what
 * happens when someone installs the site to a home screen: the name shown under
 * the icon, the splash colours, and whether it opens in a browser tab or as a
 * standalone window.
 *
 * The icons point at the 192 and 512 variants generated by src/app/icon.tsx.
 * Installability requires both of those sizes, which is the only reason
 * icon.tsx generates more than a favicon.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.name,
    short_name: site.name,
    description: site.description,
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: site.brandColor,
    // Each size is listed twice, once per purpose. An icon declared only as
    // maskable leaves a browser that wants a plain icon with none at all. The
    // spec allows a space-separated "any maskable", but Next's Manifest type
    // takes a single value, and separate entries are what Chrome documents.
    // The same image serves both: a flat square with a centred glyph survives
    // being cropped to a circle.
    icons: [
      { src: "/icon/192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon/192", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon/512", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon/512", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
